services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  WechatWorkProviderBundle\Controller\:
    resource: '../../Controller/'
  WechatWorkProviderBundle\Command\:
    resource: '../../Command/'
  WechatWorkProviderBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
  WechatWorkProviderBundle\Repository\:
    resource: '../../Repository/'
  WechatWorkProviderBundle\Service\:
    resource: '../../Service/'

  # 公开TokenManager服务用于测试
  WechatWorkProviderBundle\Service\TokenManager:
    public: true
